// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK7HpednB6oNG5pVEeo8J2i0qAd51tfD4',
    appId: '1:946943016950:android:9122f9aac14d52a5ba11d7',
    messagingSenderId: '946943016950',
    projectId: 'mini-chat-47e22',
    storageBucket: 'mini-chat-47e22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3lvPYNp5GqrQQpvB53H0zMBufyoj3MiI',
    appId: '1:946943016950:ios:85213134661c60f7ba11d7',
    messagingSenderId: '946943016950',
    projectId: 'mini-chat-47e22',
    storageBucket: 'mini-chat-47e22.firebasestorage.app',
    iosBundleId: 'com.example.miniChat.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3lvPYNp5GqrQQpvB53H0zMBufyoj3MiI',
    appId: '1:946943016950:ios:382b6988b3116e31ba11d7',
    messagingSenderId: '946943016950',
    projectId: 'mini-chat-47e22',
    storageBucket: 'mini-chat-47e22.firebasestorage.app',
    iosBundleId: 'com.example.miniChat',
  );
}
